import numpy as np
import torch
import os
import scipy.io  # Required for loading MATLAB .mat files

from potential.Periodic_Well import Periodic_Well

# ---- 1. Header and Seed ----
# Seed
SEED = 27
np.random.seed(SEED)
torch.manual_seed(SEED)

# ---- 2. General Configuration ----
ABBR = 'PW'

# Directories (Consistent with MATLAB output)
DATA_DIR = './data'
if not os.path.exists(DATA_DIR):
    os.makedirs(DATA_DIR)

FIG_DIR = 'figures'
if not os.path.exists(FIG_DIR):
    os.makedirs(FIG_DIR)

# ---- 3. Method Hyperparameters (Training & Architecture) ----

# Training Configuration
EPOCHS = 100
BATCH_SIZE = 2000
LR = 1e-4
WEIGHT_DECAY = 0.0

# Flow Architecture (Rational Quadratic Spline Flow)
# Dimensions: Input [N, 2] -> Output [N, 2]
HIDDEN_DIM = 256
NUM_LAYERS = 4
NUM_BINS = 16
DROPOUT = 0.0


# ---- 4. Data Loading (MATLAB Interface) ----

def load_data(device='cpu'):
    """
    Loads .mat files generated by MATLAB simulation.
    Returns PyTorch tensors on the specified device.

    Expected Files:
        - {ABBR}_samples_MU_0.mat (Gaussian Base Samples)
        - {ABBR}_samples_MU_1.mat (Target Samples)

    Returns:
        mu_0: Tensor [MU_SIZE, DIM] - Samples from Base (Gaussian)
        mu_1: Tensor [MU_SIZE, DIM] - Samples from Target (Three Well)
    """
    print(f"[Data] Loading MATLAB data from {DATA_DIR}...")

    # Define filenames based on ABBR
    file_0 = f'{ABBR}_samples_MU_0.mat'
    file_1 = f'{ABBR}_samples_MU_1.mat'

    path_0 = os.path.join(DATA_DIR, file_0)
    path_1 = os.path.join(DATA_DIR, file_1)

    # Check existence
    if not os.path.exists(path_0):
        raise FileNotFoundError(f"File not found: {path_0}")
    if not os.path.exists(path_1):
        raise FileNotFoundError(f"File not found: {path_1}")

    # Load MU_0 (Base Samples)
    data_0 = scipy.io.loadmat(path_0)
    mu_0_np = data_0['samples_MU_0']
    mu_0 = torch.from_numpy(mu_0_np).float().to(device)

    # Load MU_1 (Target Samples)
    data_1 = scipy.io.loadmat(path_1)
    mu_1_np = data_1['samples_MU_1']
    mu_1 = torch.from_numpy(mu_1_np).float().to(device)

    print(f"       Loaded MU_0 (Base):   {mu_0.shape}")
    print(f"       Loaded MU_1 (Target): {mu_1.shape}")

    return mu_0, mu_1

# ---- 5. Initialize Parameters ----

para = Periodic_Well()